"""
sample_hsv.py - reproduce the HSV measurement behind this project's main finding.

The module 2 README claims the LEDs are clipped to white with almost no
saturation, while the background carries strong chroma. That claim should not
have to be taken on trust, so this reads the committed frame, samples the same
regions, and prints the numbers.

Run:  python tools/sample_hsv.py
      python tools/sample_hsv.py --write     (also updates the results file)

The frame is a screen recording re-encoded as JPEG, not raw sensor data, so the
values are indicative rather than exact. The finding rests on the gap between
S = 11 and S = 246, which is far larger than compression error.
"""

import argparse
import pathlib
import sys

import cv2
import numpy as np

ROOT = pathlib.Path(__file__).resolve().parent.parent
FRAME = ROOT / "module-02-hsv-segmentation" / "images" / "02_tuned_mask.jpg"
RESULTS = ROOT / "module-02-hsv-segmentation" / "results" / "hsv_samples.md"

# Sample points inside the ORIGINAL panel (top-left quadrant of the 1920x1020
# display capture). A 7x7 median is taken at each point to reduce JPEG noise.
REGIONS = [
    ("Red LED core (left)", 541, 342),
    ("Red LED core (right)", 668, 403),
    ("Cyan/blue LED", 634, 394),
    ("Background wall", 300, 150),
    ("Breadboard body", 250, 430),
]

PATCH = 3  # half-width, so 7x7

# The bounds active in the captured frame, read off its Controls window.
S_LOWER, V_LOWER = 104, 0
RED_BANDS = [(0, 10), (170, 179)]


def in_red_bands(h):
    return any(low <= h <= high for low, high in RED_BANDS)


def sample(hsv, x, y):
    patch = hsv[y - PATCH:y + PATCH + 1, x - PATCH:x + PATCH + 1].reshape(-1, 3)
    return np.median(patch, axis=0).astype(int)


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--write", action="store_true",
                        help="write the table to module-02/results/hsv_samples.md")
    args = parser.parse_args()

    if not FRAME.exists():
        sys.exit(f"Frame not found: {FRAME}")

    image = cv2.imread(str(FRAME))
    if image is None:
        sys.exit(f"Could not decode {FRAME}")
    hsv = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)

    rows = []
    for label, x, y in REGIONS:
        h, s, v = sample(hsv, x, y)
        hue_ok = in_red_bands(h)
        if not hue_ok:
            verdict = "hue outside red bands"
        elif s < S_LOWER:
            verdict = f"hue in band but S={s} < {S_LOWER}"
        else:
            verdict = "would pass the mask"
        rows.append((label, h, s, v, verdict))

    width = max(len(r[0]) for r in rows)
    print(f"Frame: {FRAME.relative_to(ROOT).as_posix()}  ({image.shape[1]}x{image.shape[0]})")
    print(f"Active bounds in this frame: Red Mode ON, "
          f"H in {RED_BANDS[0]} or {RED_BANDS[1]}, S >= {S_LOWER}, V >= {V_LOWER}")
    print()
    print(f"{'region':<{width}}  {'H':>4} {'S':>4} {'V':>4}   result")
    print("-" * (width + 32))
    for label, h, s, v, verdict in rows:
        print(f"{label:<{width}}  {h:>4} {s:>4} {v:>4}   {verdict}")

    passing = [r for r in rows if r[4] == "would pass the mask"]
    print()
    print(f"{len(passing)} of {len(rows)} sampled regions would survive the mask.")

    leds = [r for r in rows if "LED" in r[0]]
    scene = [r for r in rows if "LED" not in r[0]]
    if leds and scene:
        led_s = max(r[2] for r in leds)
        scene_s = min(r[2] for r in scene)
        print(f"Highest LED saturation: {led_s}. Lowest background saturation: {scene_s}.")
        if scene_s > led_s:
            print("The background is more saturated than the target - the assumption "
                  "behind HSV colour thresholding is inverted here.")

    if args.write:
        lines = [
            "# HSV samples from the module 2 frame",
            "",
            "Generated by `tools/sample_hsv.py`. Re-run it to reproduce these numbers.",
            "",
            f"Source frame: `{FRAME.relative_to(ROOT).as_posix()}` "
            f"({image.shape[1]}x{image.shape[0]})",
            "",
            f"Bounds active in the capture: Red Mode ON, H in {RED_BANDS[0]} or "
            f"{RED_BANDS[1]}, S >= {S_LOWER}, V >= {V_LOWER}",
            "",
            "| Region | H | S | V | Result |",
            "|---|---:|---:|---:|---|",
        ]
        for label, h, s, v, verdict in rows:
            lines.append(f"| {label} | {h} | {s} | {v} | {verdict} |")
        lines += [
            "",
            f"{len(passing)} of {len(rows)} sampled regions would survive the mask.",
            "",
            "The LED cores are clipped (`V = 255`) with saturation in single digits,",
            "so their hue readings carry no information. The background and breadboard",
            "sit above `S = 240`. HSV thresholding assumes a saturated target against a",
            "neutral background; here that relationship is reversed.",
            "",
            "Measured from a JPEG-encoded screen recording rather than raw sensor",
            "frames, so treat the values as indicative. The gap between the LED and",
            "background saturation is far larger than compression error.",
        ]
        RESULTS.parent.mkdir(parents=True, exist_ok=True)
        RESULTS.write_text("\n".join(lines) + "\n", encoding="utf-8")
        print(f"\nwrote {RESULTS.relative_to(ROOT).as_posix()}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
